In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    "Name" : ["Taha", "Owais", "Saim"],
    "Marks" : [90, 79, 89]
})

In [4]:
df

    Name  Marks
0   Taha     90
1  Owais     79
2   Saim     89

In [12]:
df = pd.read_excel("dataset/All IL Zip Code 1.xls")
df

,zip,Zipcode name,City,State,County Name
0,61410,"ABINGDON, IL",ABINGDON,IL,NaN
1,NaN,"ADAIR, IL",NaN,IL,MCDONOUGH
2,62214,NaN,ADDIEVILLE,IL,WASHINGTON
3,60101,"ADDISON, IL",NaN,IL,DUPAGE
4,61230,"ALBANY, IL",ALBANY,NaN,WHITESIDE
...,...,...,...,...,...
1506,62999,"ZEIGLER, IL",ZEIGLER,IL,FRANKLIN
1507,60099,"ZION, IL",ZION,IL,LAKE
1508,NaN,NaN,NaN,NaN,NaN
1509,NaN,NaN,NaN,NaN,NaN
1510,"For more information, kindly visit: www.downlo...",NaN,NaN,NaN,NaN

In [13]:
df.head()

     zip  Zipcode name        City State County Name
0  61410  ABINGDON, IL    ABINGDON    IL         NaN
1    NaN     ADAIR, IL         NaN    IL   MCDONOUGH
2  62214           NaN  ADDIEVILLE    IL  WASHINGTON
3  60101   ADDISON, IL         NaN    IL      DUPAGE
4  61230    ALBANY, IL      ALBANY   NaN   WHITESIDE

In [14]:
df.dropna()

        zip    Zipcode name        City State County Name
5     62215      ALBERS, IL      ALBERS    IL     CLINTON
7     60001       ALDEN, IL       ALDEN    IL     MCHENRY
8     61231       ALEDO, IL       ALEDO    IL      MERCER
9     62601   ALEXANDER, IL   ALEXANDER    IL      MORGAN
10    61412      ALEXIS, IL      ALEXIS    IL      MERCER
...     ...             ...         ...   ...         ...
1503  62481        YALE, IL        YALE    IL      JASPER
1504  61572  YATES CITY, IL  YATES CITY    IL        KNOX
1505  60560   YORKVILLE, IL   YORKVILLE    IL     KENDALL
1506  62999     ZEIGLER, IL     ZEIGLER    IL    FRANKLIN
1507  60099        ZION, IL        ZION    IL        LAKE

[1502 rows x 5 columns]

In [16]:
df.fillna(0)

,zip,Zipcode name,City,State,County Name
0,61410,"ABINGDON, IL",ABINGDON,IL,0
1,0,"ADAIR, IL",0,IL,MCDONOUGH
2,62214,0,ADDIEVILLE,IL,WASHINGTON
3,60101,"ADDISON, IL",0,IL,DUPAGE
4,61230,"ALBANY, IL",ALBANY,0,WHITESIDE
...,...,...,...,...,...
1506,62999,"ZEIGLER, IL",ZEIGLER,IL,FRANKLIN
1507,60099,"ZION, IL",ZION,IL,LAKE
1508,0,0,0,0,0
1509,0,0,0,0,0
1510,"For more information, kindly visit: www.downlo...",0,0,0,0

In [18]:
df[["zip", "City"]]

                                                    zip        City
0                                                 61410    ABINGDON
1                                                   NaN         NaN
2                                                 62214  ADDIEVILLE
3                                                 60101         NaN
4                                                 61230      ALBANY
...                                                 ...         ...
1506                                              62999     ZEIGLER
1507                                              60099        ZION
1508                                                NaN         NaN
1509                                                NaN         NaN
1510  For more information, kindly visit: www.downlo...         NaN

[1511 rows x 2 columns]

In [20]:
df.rename(columns={"City": "Cities"})

,zip,Zipcode name,Cities,State,County Name
0,61410,"ABINGDON, IL",ABINGDON,IL,NaN
1,NaN,"ADAIR, IL",NaN,IL,MCDONOUGH
2,62214,NaN,ADDIEVILLE,IL,WASHINGTON
3,60101,"ADDISON, IL",NaN,IL,DUPAGE
4,61230,"ALBANY, IL",ALBANY,NaN,WHITESIDE
...,...,...,...,...,...
1506,62999,"ZEIGLER, IL",ZEIGLER,IL,FRANKLIN
1507,60099,"ZION, IL",ZION,IL,LAKE
1508,NaN,NaN,NaN,NaN,NaN
1509,NaN,NaN,NaN,NaN,NaN
1510,"For more information, kindly visit: www.downlo...",NaN,NaN,NaN,NaN

In [21]:
df

,zip,Zipcode name,City,State,County Name
0,61410,"ABINGDON, IL",ABINGDON,IL,NaN
1,NaN,"ADAIR, IL",NaN,IL,MCDONOUGH
2,62214,NaN,ADDIEVILLE,IL,WASHINGTON
3,60101,"ADDISON, IL",NaN,IL,DUPAGE
4,61230,"ALBANY, IL",ALBANY,NaN,WHITESIDE
...,...,...,...,...,...
1506,62999,"ZEIGLER, IL",ZEIGLER,IL,FRANKLIN
1507,60099,"ZION, IL",ZION,IL,LAKE
1508,NaN,NaN,NaN,NaN,NaN
1509,NaN,NaN,NaN,NaN,NaN
1510,"For more information, kindly visit: www.downlo...",NaN,NaN,NaN,NaN

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1511 entries, 0 to 1510
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   zip           1508 non-null   object
 1   Zipcode name  1507 non-null   object
 2   City          1506 non-null   object
 3   State         1507 non-null   object
 4   County Name   1506 non-null   object
dtypes: object(5)
memory usage: 59.2+ KB

In [30]:
df = df.dropna(subset=["zip"])
df['zip'] = df['zip'].astype(int)

ValueError: invalid literal for int() with base 10: 'For more information, kindly visit: www.downloadexcelfiles.com'

In [31]:
len(df)

1508

In [32]:
df

,zip,Zipcode name,City,State,County Name
0,61410,"ABINGDON, IL",ABINGDON,IL,NaN
2,62214,NaN,ADDIEVILLE,IL,WASHINGTON
3,60101,"ADDISON, IL",NaN,IL,DUPAGE
4,61230,"ALBANY, IL",ALBANY,NaN,WHITESIDE
5,62215,"ALBERS, IL",ALBERS,IL,CLINTON
...,...,...,...,...,...
1504,61572,"YATES CITY, IL",YATES CITY,IL,KNOX
1505,60560,"YORKVILLE, IL",YORKVILLE,IL,KENDALL
1506,62999,"ZEIGLER, IL",ZEIGLER,IL,FRANKLIN
1507,60099,"ZION, IL",ZION,IL,LAKE
1510,"For more information, kindly visit: www.downlo...",NaN,NaN,NaN,NaN

In [38]:
#df["Status"] = [0 for i in range (len(df))]
df["NewColumn"] = "Active"

C:\Users\HP\AppData\Local\Temp\ipykernel_2436\2430101248.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["NewColumn"] = "Active"