In [40]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [41]:
left_table = {'Date': ['01-01-2020', '02-01-2020', '03-01-2020', '04-01-2020' ],
              'CountryID': [1,1,3,2],
              'Units': [40, 25, 30, 35]}

In [42]:
left_table_df = pd.DataFrame(left_table)
left_table_df

         Date  CountryID  Units
0  01-01-2020          1     40
1  02-01-2020          1     25
2  03-01-2020          3     30
3  04-01-2020          2     35

In [43]:
right_table = {'CountryID': [3,4],
              'Country': ['Pandama', 'Spain']}

In [44]:
right_table_df = pd.DataFrame(right_table)
right_table_df

   CountryID  Country
0          3  Pandama
1          4    Spain

In [45]:
inner_join = left_table_df.merge(right_table_df, on ='CountryID')

In [46]:
inner_join

         Date  CountryID  Units  Country
0  03-01-2020          3     30  Pandama

In [47]:
print(left_table_df.columns)
print(right_table_df.columns)

Index(['Date', 'CountryID', 'Units'], dtype='object')
Index(['CountryID', 'Country'], dtype='object')

In [94]:
left_table_df.merge(right_table_df, left_on='CountryID', right_on='CountryID')

         Date  CountryID  Units Country_x Country_y
0  03-01-2020          3     30       IND   Pandama

In [95]:
left_table = {'Date': ['01-01-2020', '02-01-2020', '03-01-2020', '04-01-2020' ],
              'CountryID': [1,1,3,2],
              'Units': [40, 25, 30, 35],
              'Country': ['PAK','USA', 'IND', 'IRAN']
             }

In [96]:
left_table_df = pd.DataFrame(left_table)
left_table_df

         Date  CountryID  Units Country
0  01-01-2020          1     40     PAK
1  02-01-2020          1     25     USA
2  03-01-2020          3     30     IND
3  04-01-2020          2     35    IRAN

In [97]:
right_table_df

   CountryID  Country
0          3  Pandama
1          4    Spain
2          5      Pak

In [102]:
inner_join = left_table_df.merge(right_table_df, left_on='CountryID', right_on='CountryID').drop('ID', axis=1)
inner_join

KeyError: "['ID'] not found in axis"

In [72]:
left_join = left_table_df.merge(
    right_table_df,
    on='CountryID',   
    how='left',       
    suffixes=('_left', '_right')  
)
left_join

         Date  CountryID  Units Country_left Country_right
0  01-01-2020          1     40          PAK           NaN
1  02-01-2020          1     25          USA           NaN
2  03-01-2020          3     30          IND       Pandama
3  04-01-2020          2     35         IRAN           NaN

In [73]:
right_table = {'CountryID': [3,4,5],
              'Country': ['Pandama', 'Spain', 'Pak']}
right_table_df = pd.DataFrame(right_table)
right_table_df

   CountryID  Country
0          3  Pandama
1          4    Spain
2          5      Pak

In [75]:
left_join = left_table_df.merge(
    right_table_df,
    on='CountryID',
    how='left'
).drop(columns=['Country_x']).rename(columns={'Country_y': 'Country'})

left_join

         Date  CountryID  Units  Country
0  01-01-2020          1     40      NaN
1  02-01-2020          1     25      NaN
2  03-01-2020          3     30  Pandama
3  04-01-2020          2     35      NaN

In [71]:
print(left_table_df.columns.tolist())

['Date', 'CountryID', 'Units', 'Country']

### Task

In [80]:
left_table1 = {'Date': ['01-01-2020', '02-01-2020', '03-01-2020', '04-01-2020' ],
              'CountryID': [1,1,3,2],
              'Units': [40, 25, 30, 35]}
left_table1_df = pd.DataFrame(left_table1)
left_table1_df

         Date  CountryID  Units
0  01-01-2020          1     40
1  02-01-2020          1     25
2  03-01-2020          3     30
3  04-01-2020          2     35

In [91]:
right_table1 = {'ID': [3,4],
              'Country': ['Pandama', 'Spain']}
right_table1_df = pd.DataFrame(right_table1)
right_table1_df

   ID  Country
0   3  Pandama
1   4    Spain

In [92]:
left_table1_df.merge(right_table1_df, left_on='CountryID', right_on='ID')

         Date  CountryID  Units  ID  Country
0  03-01-2020          3     30   3  Pandama

In [100]:
left_table1_df.merge(right_table1_df, left_on='CountryID', right_on='ID').drop('ID', axis=1)

         Date  CountryID  Units  Country
0  03-01-2020          3     30  Pandama

## Full/Outer Join

In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [9]:
left_table = {'Date': ['01-01-2020', '02-01-2020', '03-01-2020', '04-01-2020','04-01-2025' ],
              'CountryID': [1,1,3,2,5],
              'Units': [40, 25, 30, 35, 55]}

left_table_df = pd.DataFrame(left_table)
left_table_df

         Date  CountryID  Units
0  01-01-2020          1     40
1  02-01-2020          1     25
2  03-01-2020          3     30
3  04-01-2020          2     35
4  04-01-2025          5     55

In [10]:
right_table = {'ID': [1,2,3,4],
              'Country': ['USA', 'Canada', 'Panama', 'Spain']}

right_table_df = pd.DataFrame(right_table)
right_table_df

   ID Country
0   1     USA
1   2  Canada
2   3  Panama
3   4   Spain

In [15]:
outer_join = left_table_df.merge(right_table_df, left_on='CountryID', right_on='ID', how='outer')
outer_join

         Date  CountryID  Units   ID Country
0  01-01-2020        1.0   40.0  1.0     USA
1  02-01-2020        1.0   25.0  1.0     USA
2  04-01-2020        2.0   35.0  2.0  Canada
3  03-01-2020        3.0   30.0  3.0  Panama
4         NaN        NaN    NaN  4.0   Spain
5  04-01-2025        5.0   55.0  NaN     NaN

In [16]:
outer_join = left_table_df.merge(right_table_df, left_on='CountryID', right_on='ID', how='outer').drop('ID', axis=1)
outer_join

         Date  CountryID  Units Country
0  01-01-2020        1.0   40.0     USA
1  02-01-2020        1.0   25.0     USA
2  04-01-2020        2.0   35.0  Canada
3  03-01-2020        3.0   30.0  Panama
4         NaN        NaN    NaN   Spain
5  04-01-2025        5.0   55.0     NaN

## Left Anti Join

In [34]:
left_table = {'Data': ['01-01-2020', '02-01-2020', '03-01-2020', '04-01-2020' ],
            'CountryID': [1,1,3,2],
            'Units': [40,25,30,35]
           }
left_table_df = pd.DataFrame(left_table)
left_table_df

         Data  CountryID  Units
0  01-01-2020          1     40
1  02-01-2020          1     25
2  03-01-2020          3     30
3  04-01-2020          2     35

In [35]:
right_table = {'ID': [3,4],
                'Country': ['Panama', 'Spain']
              }
right_table_df = pd.DataFrame(right_table)
right_table_df

   ID Country
0   3  Panama
1   4   Spain

In [36]:
left_join_df = left_table_df.merge(right_table_df, left_on='CountryID', right_on='ID', how='left')
left_join_df

         Data  CountryID  Units   ID Country
0  01-01-2020          1     40  NaN     NaN
1  02-01-2020          1     25  NaN     NaN
2  03-01-2020          3     30  3.0  Panama
3  04-01-2020          2     35  NaN     NaN

In [37]:
left_join_df = left_table_df.merge(right_table_df, left_on='CountryID', right_on='ID', how='left').drop('ID', axis=1)
left_join_df

         Data  CountryID  Units Country
0  01-01-2020          1     40     NaN
1  02-01-2020          1     25     NaN
2  03-01-2020          3     30  Panama
3  04-01-2020          2     35     NaN

In [38]:
left_join_df = left_table_df.merge(right_table_df, left_on='CountryID', right_on='ID', how='left', indicator=True).drop('ID', axis=1)
left_join_df

         Data  CountryID  Units Country     _merge
0  01-01-2020          1     40     NaN  left_only
1  02-01-2020          1     25     NaN  left_only
2  03-01-2020          3     30  Panama       both
3  04-01-2020          2     35     NaN  left_only

In [48]:
left_join_df.loc[left_join_df['_merge'] == 'left_only']

         Data  CountryID  Units Country     _merge
0  01-01-2020          1     40     NaN  left_only
1  02-01-2020          1     25     NaN  left_only
3  04-01-2020          2     35     NaN  left_only

In [49]:
left_only_ids

         Data  CountryID  Units Country     _merge
0  01-01-2020          1     40     NaN  left_only
1  02-01-2020          1     25     NaN  left_only
2  03-01-2020          3     30  Panama       both
3  04-01-2020          2     35     NaN  left_only

In [50]:
left_join_df[left_join_df['CountryID'].isin(left_only_ids)]

Empty DataFrame
Columns: [Data, CountryID, Units, Country, _merge]
Index: []

## Right Anti Join

In [51]:
left_table = {'Data': ['01-01-2020', '02-01-2020', '03-01-2020', '04-01-2020' ],
            'CountryID': [1,1,3,2],
            'Units': [40,25,30,35]
           }
left_table_df = pd.DataFrame(left_table)
left_table_df

         Data  CountryID  Units
0  01-01-2020          1     40
1  02-01-2020          1     25
2  03-01-2020          3     30
3  04-01-2020          2     35

In [74]:
right_table = {'ID': [3,4],
                'Country': ['Panama', 'Spain']
              }
right_table_df = pd.DataFrame(right_table)
right_table_df

   ID Country
0   3  Panama
1   4   Spain

In [75]:
right_join_df = left_table_df.merge(right_table_df, left_on='CountryID', right_on='ID', how='right')
right_join_df

         Data  CountryID  Units  ID Country
0  03-01-2020        3.0   30.0   3  Panama
1         NaN        NaN    NaN   4   Spain

In [76]:
right_join_df = left_table_df.merge(right_table_df, left_on='CountryID', right_on='ID', how='right').drop('ID', axis=1)
right_join_df

         Data  CountryID  Units Country
0  03-01-2020        3.0   30.0  Panama
1         NaN        NaN    NaN   Spain

In [77]:
right_join_df = left_table_df.merge(right_table_df, left_on='CountryID', right_on='ID', how='left', indicator=True).drop('ID', axis=1)
right_join_df

         Data  CountryID  Units Country     _merge
0  01-01-2020          1     40     NaN  left_only
1  02-01-2020          1     25     NaN  left_only
2  03-01-2020          3     30  Panama       both
3  04-01-2020          2     35     NaN  left_only

In [78]:
right_join_df.loc[right_join_df['_merge'] == 'right_only']

Empty DataFrame
Columns: [Data, CountryID, Units, Country, _merge]
Index: []

## Concatenation

In [81]:
left_join_df

         Data  CountryID  Units Country     _merge
0  01-01-2020          1     40     NaN  left_only
1  02-01-2020          1     25     NaN  left_only
2  03-01-2020          3     30  Panama       both
3  04-01-2020          2     35     NaN  left_only

In [83]:
right_join_df

         Data  CountryID  Units Country     _merge
0  01-01-2020          1     40     NaN  left_only
1  02-01-2020          1     25     NaN  left_only
2  03-01-2020          3     30  Panama       both
3  04-01-2020          2     35     NaN  left_only